labels:
  bug: ["error", "panic", "throw", "crash", "exception"]
  docs: ["readme", "typo", "docs", "documentation"]
priorities:
  P0: ["panic", "security", "data loss", "crash"]
  P1: ["regression", "blocking", "broken"]
areas: ["crawler", "pipeline", "api", "docs", "sdk"]

conventions:
  # This keeps CI fast and avoids pulling in the whole monorepo test matrix.
  testCmd: pnpm exec vitest run tests/agent --reporter=default --passWithNoTests

  # Paths the agent is allowed to touch when generating diffs
  whitelistPaths:
    - tests/agent/
    - tools/
    - packages/
    - src/
    - apps/
    - docs/
    - CHANGELOG.md
