name: Agent Docs Updater
on:
  pull_request:
    types: [closed]
permissions:
  contents: write
jobs:
  docs:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - run: pnpm install
      - run: pnpm agent:docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
